// *** This file is automatically generated - Do not edit! ***
/* tslint:disable */
/* eslint-disable */

declare const styles = {
  main: 'App__main--OYDfP',
  article: 'App__article--xSqYE',
  logo: 'App__logo--gAm0e',
  description: 'App__description--lEWQu',
  header: 'App__header--trrtU',
  list: 'App__list--TH3nr',
} as const;

export type ClassName = string;

export default styles;
