// *** This file is automatically generated - Do not edit! ***
/* tslint:disable */
/* eslint-disable */

declare const styles = {
    'main': 'App__main--OYDfP',
    'article': 'App__article--xSqYE',
    'logo': 'App__logo--gAm0e',
    'header': 'App__header--trrtU',
} as const;

export type ClassName = string;

export default styles;