name: React TS Starter workflow
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  main: 
    name: Build
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14.20.x'
      - name: Install dependencies
        run: yarn
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Lint tests
        run: yarn run lint:check
      - name: Run Jest tests
        run: yarn run test:unit
      - name: Run Playwright tests
        run: yarn playwright test
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: Build
        run: yarn run build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build~
